version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-your_development_secret_key}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres:17
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-rac_website}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      
  nginx:
    image: nginx:latest
    command: /bin/bash -c "echo 'client_max_body_size 20M;' > /etc/nginx/conf.d/client_max_body_size.conf && nginx -g 'daemon off;'"
    # Change this line in your docker-compose.yml
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
    restart: always

volumes:
  pgdata:
