# Generated by Django 3.2.25 on 2025-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
