# Generated by Django 3.2.25 on 2025-04-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date_published', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('descriptions_json', models.TextField(default='[]')),
                ('requirements_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
