# Generated by Django 3.2.25 on 2025-04-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
