# Generated by Django 3.2.25 on 2025-04-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0005_service_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='contacts',
        ),
        migrations.AddField(
            model_name='service',
            name='contacts_json',
            field=models.TextField(default='[]'),
        ),
    ]
