# Generated by Django 3.2.25 on 2025-04-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0006_auto_20250403_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='contacts_json',
        ),
    ]
