# Generated by Django 3.2.25 on 2025-04-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0007_remove_service_contacts_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contacts_json',
            field=models.TextField(default='[]'),
        ),
    ]
