# Generated by Django 3.2.25 on 2025-04-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0008_service_contacts_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='contacts_json',
        ),
    ]
