# Generated by Django 3.2.25 on 2025-04-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rac_blog', '0009_remove_service_contacts_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
